
import React from 'react';
import { RedesignData, ContentBlock } from '../types';

/**
 * Utility to clean academic text from markdown artifacts like asterisks
 * commonly generated by LLMs for bolding/emphasis.
 */
const cleanAcademicText = (text: string): string => {
  if (!text) return "";
  // Removes asterisks used for bolding/italics/lists to keep a clean academic look
  return text.replace(/\*/g, '');
};

const MarkdownTable: React.FC<{ content: string; primaryColor: string }> = ({ content, primaryColor }) => {
  const rows = content.trim().split('\n').filter(r => r.includes('|'));
  if (rows.length < 2) return null;

  const headerIdx = 0;
  const separatorIdx = rows.findIndex(r => r.includes('---') || r.includes('==='));
  const bodyStartIdx = separatorIdx !== -1 ? separatorIdx + 1 : 1;

  const headers = rows[headerIdx]
    .split('|')
    .filter(c => c.trim())
    .map(c => cleanAcademicText(c.trim()));

  const bodyRows = rows.slice(bodyStartIdx).map(r => 
    r.split('|')
      .filter(c => c.trim())
      .map(c => cleanAcademicText(c.trim()))
  );

  return (
    <div 
      className="my-8 overflow-hidden rounded-lg border-2 break-inside-avoid page-break-inside-avoid max-w-full"
      style={{ borderColor: primaryColor, boxShadow: `4px 4px 0px 0px ${primaryColor}` }}
    >
      <div className="overflow-x-auto w-full">
        <table className="w-full text-left text-sm border-collapse table-auto min-w-full">
          <thead style={{ backgroundColor: primaryColor }} className="text-white uppercase text-[10px] tracking-widest font-black">
            <tr>
              {headers.map((h, i) => (
                <th key={i} className="px-5 py-4 border-r border-white/20 last:border-0 whitespace-nowrap">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y-2 bg-white" style={{ borderColor: primaryColor }}>
            {bodyRows.map((row, i) => (
              <tr key={i} className={`${i % 2 === 0 ? 'bg-white' : 'bg-slate-50'} break-inside-avoid`}>
                {row.map((cell, j) => (
                  <td 
                    key={j} 
                    className="px-5 py-4 text-slate-900 border-r-2 last:border-0 font-medium align-top break-words"
                    style={{ borderRightColor: primaryColor }}
                  >
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const CalloutBox: React.FC<{ block: ContentBlock; color: string }> = ({ block, color }) => {
  const label = block.label || "INFO";
  const isExamTip = label.toUpperCase().includes("EXAM");
  const isMemoryTrick = label.toUpperCase().includes("MEMORY");
  
  return (
    <div 
      className={`my-8 p-6 rounded-xl border-2 shadow-[4px_4px_0px_0px] ${
        isExamTip ? 'bg-amber-50' : isMemoryTrick ? 'bg-indigo-50' : 'bg-slate-50'
      } max-w-full overflow-hidden break-inside-avoid page-break-inside-avoid`}
      style={{ 
        borderColor: color, 
        boxShadow: `4px 4px 0px 0px ${color}` 
      }}
    >
      <div className="flex items-center gap-2 mb-4">
        <span 
          style={{ backgroundColor: color }}
          className="text-white px-3 py-1 text-[10px] font-black tracking-widest rounded-md uppercase"
        >
          {label}
        </span>
      </div>
      <div className="text-slate-900 text-lg font-bold academic-serif leading-relaxed italic break-words whitespace-pre-wrap">
        {cleanAcademicText(block.content)}
      </div>
    </div>
  );
};

const RenderBlock: React.FC<{ block: ContentBlock; primaryColor: string }> = ({ block, primaryColor }) => {
  if (!block.content) return null;
  
  const cleanedContent = cleanAcademicText(block.content);

  switch (block.type) {
    case 'subheading':
      return (
        <h4 className="text-2xl font-black text-slate-900 mt-12 mb-6 flex items-center gap-4 break-words break-after-avoid">
          <span className="w-10 h-1.5 rounded-full flex-shrink-0" style={{ backgroundColor: primaryColor }}></span>
          {cleanedContent}
        </h4>
      );
    case 'paragraph':
      return (
        <p className="text-slate-800 leading-[1.8] mb-8 academic-serif text-[1.15rem] text-justify break-words break-inside-avoid">
          {cleanedContent}
        </p>
      );
    case 'list':
      const items = String(block.content).split('\n').filter(i => i.trim());
      return (
        <div className="mb-10 pl-4 border-l-4 border-slate-200 space-y-4 max-w-full">
          {items.map((item, i) => (
            <div key={i} className="flex gap-4 items-start break-inside-avoid">
              <span className="flex-shrink-0 w-2 h-2 rounded-full mt-2.5" style={{ backgroundColor: primaryColor }}></span>
              <span className="text-slate-800 academic-serif text-[1.15rem] font-medium leading-relaxed break-words">
                {cleanAcademicText(item.replace(/^[-*]\s*/, ''))}
              </span>
            </div>
          ))}
        </div>
      );
    case 'table':
      return <MarkdownTable content={block.content} primaryColor={primaryColor} />;
    case 'callout':
      return <CalloutBox block={block} color={primaryColor} />;
    default:
      return null;
  }
};

const RedesignPreview: React.FC<{ data: RedesignData }> = ({ data }) => {
  const primaryColor = data.themeColors.primary || '#0f172a';

  return (
    <div className="pb-32 overflow-x-hidden" style={{ counterReset: 'page-counter' }}>
      <div id="pdf-content" className="print-page academic-serif relative overflow-hidden text-slate-900 bg-white mx-auto max-w-full">
        
        {/* Institutional Header */}
        <header className="mb-16 border-b-[6px] pb-12 mt-4 relative break-inside-avoid" style={{ borderColor: primaryColor }}>
          <div className="flex justify-between items-start mb-12 gap-4">
            <div className="flex flex-col gap-3 min-w-0">
              <div 
                style={{ backgroundColor: primaryColor }}
                className="text-white px-3 py-1 text-[10px] font-black tracking-[0.3em] uppercase rounded w-fit"
              >
                Namma Vtu Bros
              </div>
              <div className="flex flex-col gap-1">
                <div 
                  className="font-black text-xs border-l-4 pl-3 uppercase tracking-tighter break-words"
                  style={{ borderColor: primaryColor, color: primaryColor }}
                >
                  Reference: Gurugalee
                </div>
              </div>
            </div>
          </div>
          
          <h1 className="text-6xl sm:text-7xl font-black leading-[1.1] tracking-tight text-slate-900 mb-6 uppercase break-words">
            {data.documentTitle}
          </h1>
        </header>

        {/* Content Body - Continuous Flow */}
        <div className="space-y-0">
          {data.sections.map((section, idx) => (
            <article 
              key={idx} 
              className="relative max-w-full py-12 first:pt-0 border-b-2 border-slate-50 last:border-0"
              style={{ 
                pageBreakBefore: 'auto',
                breakBefore: 'auto',
                counterIncrement: 'page-counter'
              }}
            >
              {/* Section Header */}
              <div className="flex items-center gap-6 mb-10 group max-w-full break-after-avoid break-inside-avoid">
                <span className="text-6xl font-black text-slate-200 leading-none group-hover:text-slate-900 transition-colors flex-shrink-0">
                  {String(idx + 1).padStart(2, '0')}
                </span>
                <div className="flex-1 border-b-4 border-slate-100 pb-2 min-w-0">
                  <h2 className="text-4xl font-black tracking-tight text-slate-900 uppercase break-words">
                    {section.title}
                  </h2>
                </div>
              </div>
              
              {/* Blocks */}
              <div className="pl-2 max-w-full overflow-hidden">
                {section.blocks.map((block, bIdx) => (
                  <RenderBlock key={bIdx} block={block} primaryColor={primaryColor} />
                ))}
              </div>
            </article>
          ))}
        </div>

        {/* Final Footer */}
        <footer 
          className="mt-32 pt-16 border-t-4 flex justify-between items-center text-[10px] text-slate-900 font-black tracking-[0.4em] uppercase gap-4"
          style={{ borderColor: primaryColor, breakInside: 'avoid' }}
        >
          <div className="flex items-center gap-3">
             <div className="w-4 h-4 rounded-sm rotate-45" style={{ backgroundColor: primaryColor }}></div>
             Thanks to GURUGALE
          </div>
          <div>© Namma Vtu Bros</div>
        </footer>
      </div>
      
      {/* Dynamic Page Counter styling for System Print */}
      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body { counter-reset: page; }
          .print-page::after {
            content: "Page " counter(page);
            counter-increment: page;
            position: fixed;
            bottom: 20px;
            right: 20px;
            font-size: 10px;
            font-weight: 900;
            letter-spacing: 0.2em;
            text-transform: uppercase;
            color: #94a3b8;
          }
          /* Fix for vertical content clipping: prevent breaking inside blocks */
          p, h1, h2, h3, h4, h5, h6, li, tr, .break-inside-avoid {
            break-inside: avoid;
            page-break-inside: avoid;
            display: block; /* Required for some browsers to respect break-inside */
          }
          /* Prevent half-word vertical splits */
          p, td, li, span {
            orphans: 3;
            widows: 3;
          }
          /* Specific table row split prevention */
          tr {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
        }
      `}} />
    </div>
  );
};

export default RedesignPreview;
